### ISSUE TITLE
Enable compression for cwr.js

### ISSUE THREAD

**Issue by blimmer** [aws-observability/aws-rum-web#102]
Today, the text of `cwr.js` is not compressed:

<img width="1011" alt="Screen Shot 2022-02-24 at 18 43 12" src="https://user-images.githubusercontent.com/630449/155638453-b7456f76-b089-47cd-92b7-b6d977ff8852.png">

Since this is served via CloudFront (I'm assuming with an S3 backend), you should be able to simply [enable automatic compression](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html?icmpid=docs_cf_help_panel#DownloadDistValuesCompressObjectsAutomatically) on the distribution, which should clear this error.

**Comment by qhanam** [comment]
Thanks @blimmer ! We will look into this.

**Comment by adebayor123** [comment]
Hi @blimmer ! We now support compression for all versions of application monitors. Thank you for bringing this up.

**Comment by blimmer** [comment]
Great! I confirmed this on my site that uses it. Thanks 👍
