### ISSUE TITLE
Ignore errors with matching pattern configuration please.

### ISSUE THREAD

**Issue by AntiMoron** [aws-observability/aws-rum-web#119]
Expecting:

```
{
          sessionSampleRate: 1,
          guestRoleArn:
            'arn:aws:iam::xxxxxxxx',
          identityPoolId: 'us-west-xxxxxxxxx',
          endpoint: 'https://dataplane.rum.us-west-2.amazonaws.com',
          telemetries: ['performance', 'errors', 'http'],
          allowCookies: true,
          enableXRay: true,
          pageIdFormat: 'PATH_AND_HASH',
/////// if the following configuration matches an error then ignore it.
          ignoreErrors: [
              /ResizeObserver loop limit exceeded/g,  // <---------- Focus here please.
              /Script error\./g,  // <---------- Focus here please.
          ]
},
```

**Comment by qhanam** [comment]
Hi @AntiMoron thanks for this request! We'll take a look.

I do think something like this is needed, either to ignore certain errors, dedup errors, or both.

**Comment by AntiMoron** [comment]
@qhanam Yeah, It's quite common feature in similar products nowadays. But I trust AWS more!!

**Comment by AntiMoron** [comment]
If any updates about this please let me know.

**Comment by AntiMoron** [comment]
Some scenes of this feature in real life engineering:
1. Some chrome plugins may cause js error.
2. Some error such as `ResizeObserver loop limit exceeded` only comes from some 17ms time exceed in `requestAnimationFrame` which is no big use to web devs.
3. Some script error comes from setTimeout/setInterval callback function. If you can hook `setTimeout` that would be nice. Currently I prefer to ignore those errors.

**Comment by AntiMoron** [comment]
@qhanam Hi, can I have some progress info about this feature?

**Comment by qhanam** [comment]
Hi @AntiMoron no one has picked this up yet.

**Comment by AntiMoron** [comment]
@qhanam Can I ask if this is a pure frontend function, or this is related to backend?

I want to know if this is workable with open source pull requests.

**Comment by qhanam** [comment]
Exactly -- this is the question we haven't looked into.

I think it could be a pure frontend function, especially as a quick solution. For example, we could add a configuration option to [`JsErrorPlugin`](https://github.com/aws-observability/aws-rum-web/blob/main/src/plugins/event-plugins/JsErrorPlugin.ts) which holds a callback function (call it `ignore` for now). When `JsErrorPlugin` receives an error, it passes it to the `ignore` function, which returns `true` if the error should be dropped, and `false` if the error should be dispatched to the RUM app monitor.

In this case, applications would provide their own filter mechanism. What do you think? Would this solution work for this use case?

A backend approach could potentially automatically filter common errors which are not directly related to the application. However this would take considerable time to implement.

**Comment by qhanam** [comment]
@adebayor123 is looking into this issue

**Comment by AntiMoron** [comment]
Thanks a lot!
