### ISSUE TITLE
Enforce strict type checks with TypeScript

### ISSUE THREAD

**Issue by qhanam** [aws-observability/aws-rum-web#12]
Strict type checks in TypeScript gives stronger guarantees about types, but are not currently enforced.

This task is to (1) update tsconfig.json to include `"strict": true` in `compilerOptions` and (2) fix any TypeScript compiler errors with the new configuration.

**Comment by thankyouveryfun** [comment]
is anyone working on this?
I could take a stab at it

**Comment by qhanam** [comment]
@thankyouveryfun no one is currently working on this. We do accept and appreciate PRs and are happy to work with you if you would like to work on it.

**Comment by maniator** [comment]
This _may_ be covered by work on https://github.com/aws-observability/aws-rum-web/issues/9

**Comment by tlakomy** [comment]
👋 Are there plans to resolve this issue? It seems that there's quite a lot of TS errors when enabling `strict` mode on `main` branch:

![image](https://user-images.githubusercontent.com/16646517/191975743-9bcfa9a1-e1aa-4718-afd1-53849db9d01d.png)

I wanted to give it a shot myself, but at >300 errors this would take me a substantial amount of time given that I'm not familiar with the codebase.

**Comment by qhanam** [comment]
Yes there are a lot -- frankly it's a bit daunting for us too.
