### ISSUE TITLE
The ability to add labels

### ISSUE THREAD

**Issue by tomsender** [aws-observability/aws-rum-web#127]
Adding labels/tags is essential in order to analyze the page performance.
For example - account_id, page_name and more

Is it possible to send a label/tag?

Other tools support it:
https://support.speedcurve.com/docs/rum-page-labels
https://docs.sentry.io/platforms/python/enriching-events/tags/

**Comment by qhanam** [comment]
Hi @tomsender thanks for raising this!

We've just added a feature that allows tags to be added to page views. See the [recordPageView command](https://github.com/aws-observability/aws-rum-web/blob/main/docs/cdn_commands.md#commands).

E.g.,
```
const awsRum: AwsRum = new AwsRum(
  APPLICATION_ID,
  APPLICATION_VERSION,
  APPLICATION_REGION,
  config
);
...
awsRum.recordPageView({ pageId: '/home', pageTags: ['en', 'landing']});
```

Does this feature fit your use case?

Note that the page view automation (`PageViewPlugin`) does not currently support page tags, so to use this feature you will need to manually record page views using `recordPageView`. If you would like support added to `PageViewPlugin`, please +1 this issue to help us prioritize.

**Comment by Anntoin** [comment]
@qhanam Should tags also replace the recommendation to record custom pageids for react apps https://github.com/aws-observability/aws-rum-web/blob/main/docs/cdn_react.md#instrument-routing-to-record-page-views

**Comment by qhanam** [comment]
Tags is an addition to page IDs.

Tags should maybe be read as "page groups". It is a way for you to define, in your web application code, sets of pages with related characteristics. The data for these page groups can then be easily aggregated (e.g., in the CloudWatch RUM console). For example, this is useful if I want to see the average page load time across all landing pages.

A page ID is still required to uniquely identify the UI that the user is interacting with.

Or am I miss-understanding the question? Please let me know :-).

**Comment by qhanam** [comment]
CloudWatch RUM now supports the ability to tag pages with a "page group".
