### ISSUE TITLE
Why the use of both playwrite and testcafe

### ISSUE THREAD

**Issue by maniator** [aws-observability/aws-rum-web#147]
Would it make sense just to use one of them?

**Comment by maniator** [comment]
Now I see there is _also_ nightwatch

**Comment by adebayor123** [comment]
Yes, we do plan to migrate to a single framework for our integ tests. We will most likely migrate to Playwright entirely, but it will require rewriting of all our integ test cases, so it is in our backlog.

**Comment by maniator** [comment]
@adebayor123 is there a public GitHub project board that can be tracked?
