### ISSUE TITLE
Potential slowdown of site due to listening for global keydown events

### ISSUE THREAD

**Issue by maniator** [aws-observability/aws-rum-web#168]
In the [`VirtualPageLoadTimer` plugin](https://github.com/aws-observability/aws-rum-web/blob/main/src/sessions/VirtualPageLoadTimer.ts#L81) on line 81 it has a keydown event, which if a user holds down a key it will get hit every ms until they list their finger from the keyboard.

I think there are two options to fix this issue:

1.  debounce the event for keydown
     Down side to this is that we may not get the most accurate information, and the debounce method still gets hit every ms
2. figure out a better option for detecting a page interaction without hitting the same method n number of times per second

**Comment by adebayor123** [comment]
As discussed offline, `keyup` event and `mouseup` event would be a better solution, as it would not be triggered every ms.

**Comment by maniator** [comment]
I think I may have a solution without any mouse or key events.

May push PR today or Tuesday
