### ISSUE TITLE
Use enhanced authflow

### ISSUE THREAD

**Issue by zoellner** [aws-observability/aws-rum-web#172]
Currently, rum uses the basic (classic) authflow. Would it be possible to switch (maybe with a config option) to the Enhanced (simplified) authflow?
Both are documented here:
https://docs.aws.amazon.com/cognito/latest/developerguide/authentication-flow.html

Reason for the request is that the basic authflow does not work with RoleMappings. 
Error message is `Basic (classic) flow is not supported with RoleMappings, please use enhanced flow.`
`

**Comment by qhanam** [comment]
Hi @zoellner we're working on it :-) 

For unauthenticated identities, ["Cognito applies a scope-down policy to credentials vended by `GetCredentialForIdentity`"](https://docs.aws.amazon.com/cognito/latest/developerguide/iam-roles.html#access-policies). This is currently preventing the web client from using the enhanced authflow. 

We're working with Cognito to get CloudWatch RUM added to this list of services. Once that happens, simply omitting the `guestRoleArn` from the config will cause the web client to use the [enhanced authflow](https://github.com/aws-observability/aws-rum-web/blob/main/src/dispatch/EnhancedAuthentication.ts). Unfortunately I cannot provide an ETA, but requests like this one help us get it prioritized.

For authenticated identities, this does not apply -- you must instrument your own authflow, which can use Cognito's enhanced authflow.

**Comment by qhanam** [comment]
You can now used Cognito's enhanced authflow with CloudWatch RUM. To use enhanced authflow, simply omit `guestRoleArn` from the web client configuration. For example:

```diff
import { AwsRum, AwsRumConfig } from 'aws-rum-web';

try {
  const config: AwsRumConfig = {
    allowCookies: true,
    endpoint: "https://dataplane.rum.us-west-2.amazonaws.com",
-    guestRoleArn: "arn:aws:iam::000000000000:role/RUM-Monitor-us-west-2-000000000000-00xx-Unauth",
    identityPoolId: "us-west-2:00000000-0000-0000-0000-000000000000",
    sessionSampleRate: 1,
    telemetries: ['errors', 'performance']
  };

  const APPLICATION_ID: string = '00000000-0000-0000-0000-000000000000';
  const APPLICATION_VERSION: string = '1.0.0';
  const APPLICATION_REGION: string = 'us-west-2';

  const awsRum: AwsRum = new AwsRum(
    APPLICATION_ID,
    APPLICATION_VERSION,
    APPLICATION_REGION,
    config
  );
} catch (error) {
  // Ignore errors thrown during CloudWatch RUM web client initialization
}
```

**Comment by williazz** [comment]
Closing because EnhancedAuthentication with Cognito is supported.
