### ISSUE TITLE
Getting approval requests for deployments 

### ISSUE THREAD

**Issue by anuraaga** [aws-observability/aws-rum-web#183]
Hello - I seem to still get approval requests for deployments in this repo even though I'm not at AWS anymore. I couldn't find a reference to my user in this repo, so not sure why but would be good if that could be sorted. Thanks.

/cc @Aneurysm9

**Comment by anuraaga** [comment]
Still getting - @qhanam can you take a look?

**Comment by qhanam** [comment]
Sorry about that -- fixed!
