### ISSUE TITLE
Error filtering doesn't filter errors caused by browser extensions

### ISSUE THREAD

**Issue by omerfarukaslan** [aws-observability/aws-rum-web#189]
Error ignore feature doesn't filter out errors caused by browser extensions. such as `@moz-extension` and `chrome-extension`.

Using the error handler function like this:
```
export const rumErrorHandler = (
  errorEvent: ErrorEvent | PromiseRejectionEvent
): boolean => {
  if (!(errorEvent instanceof ErrorEvent)) {
    return false;
  }
  const errorPatterns = [
    /chrome-extension/,
    /moz-extension/,
    /ResizeObserver loop/,
  ];

  return errorPatterns.some(
    (errorPattern) =>
      errorPattern.test(errorEvent.error?.stack) ||
      errorPattern.test(errorEvent.filename) ||
      errorPattern.test(errorEvent.message)
  );
};
```

In addition to this issue, that would be also great to be able to filter out 4XX errors.

Thank you.

**Comment by adebayor123** [comment]
After doing some testing, I noticed that (1) the regex expressions are fine, and (2) the behavior of not being able to filter is not restricted to errors caused by browser extensions, but rather due to being in the `error?.stack` field.

Once I placed the example stack messages @omerfarukaslan shared into the Error.message field, the filtering worked correctly.

**Comment by qhanam** [comment]
@adebayor123 so is this an issue with the filter function then? Or is this something in the web client?

**Comment by qhanam** [comment]
> In addition to this issue, that would be also great to be able to filter out 4XX errors.

We treat codes which indicate a server error a little differently than JavaScript errors.

So the question is, should we overload the `ignore` config function by including HTTP responses, or create a new config option?

**Comment by omerfarukaslan** [comment]
> > In addition to this issue, that would be also great to be able to filter out 4XX errors.
> 
> We treat codes which indicate a server error a little differently than JavaScript errors.
> 
> So the question is, should we overload the `ignore` config function by including HTTP responses, or create a new config option?

I would be in favor of overloading the ignore function.

**Comment by adebayor123** [comment]
@qhanam I just saw this notification - back when this issue first was raised by omerfarukaslan@, I wasn't able to fully reproduce the issue. 
@omerfarukaslan were you able to find the root cause of the issue?

**Comment by omerfarukaslan** [comment]
Unfortunately I couldn't find the root cause.

**Comment by adebayor123** [comment]
Synced up with omerfarukaslan@ yesterday, the issue could be that the browser extension specific errors could be a `PromiseRejectionEvent`, which is set to return False in the error filtering method above. He stated he will try testing and get back with the result.

**Comment by omerfarukaslan** [comment]
It turns out browser extension errors were not getting filtered due to `PromiseRejectionEvent`s were not handled on my code. Updating the code like below fixed the issue. 

`export const rumErrorHandler = (
  event: ErrorEvent | PromiseRejectionEvent
): boolean => {
  return errorEventHandler(
    event instanceof ErrorEvent
      ? event
      : ({
          type: event.type,
          error: event.reason,
        } as ErrorEvent)
  );
};

const errorEventHandler = (errorEvent: ErrorEvent): boolean => {
  const errorPatterns = [
    /chrome-extension/,
    /moz-extension/,
    /ResizeObserver loop/,
  ];
  return errorPatterns.some(
    (errorPattern) =>
      errorPattern.test(errorEvent.error?.stack) ||
      errorPattern.test(errorEvent.filename) ||
      errorPattern.test(errorEvent.message)
  );
};

`
