### ISSUE TITLE
Question: is `interaction` telemetry ready to be used?

### ISSUE THREAD

**Issue by tlakomy** [aws-observability/aws-rum-web#232]
While browsing this repo I've noticed this section on `interaction` telemetry:

https://github.com/aws-observability/aws-rum-web/blob/main/docs/configuration.md#interaction

As far as I can tell this is not documented anywhere else (https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-RUM.html) and it's unclear to me whether I can try to use it to record DOM events.

Thank you in advance 🙏

**Comment by qhanam** [comment]
The `interaction` telemetry is safe to use for recording DOM events. For example, if I wanted to record clicks on elements with attribute `data-rum="record_this` or `data-rum="record_that"`, then I might configure the web client (the `interaction` telemetry specifically) like so:

```typescript
  const config: AwsRumConfig = {
    sessionSampleRate: 1,
    endpoint: "https://dataplane.rum.us-west-2.amazonaws.com",
    telemetries: [
        "performance",
        "errors",
        "http",
        [ "interaction", {
                interactionId: (e) => event.target.getAttribute("data-rum"),
                enableMutationObserver: true,
                events: [
                    { event: 'click', cssLocator: '[data-rum="record_this"]' },
                    { event: 'click', cssLocator: '[data-rum="record_that"]' },
                ] 
            }
        ],
    allowCookies: true
  };
```

**Comment by tlakomy** [comment]
@qhanam thanks for the answer! Once I set up an `interaction` telemetry, how can I see the recorded clicks?

**Comment by qhanam** [comment]
@tlakomy the CloudWatch RUM console doesn't show click metrics yet. A workaround is to export the data to CloudWatch Logs. From there you can [create metrics](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CreateMetricFilterProcedure.html) and dashboards for DOM events, and search the raw events using CloudWatch Insights queries.
