### ISSUE TITLE
"CWR: Failed to retrieve credentials from STS" error thrown by aws-rum-web

### ISSUE THREAD

**Issue by tlakomy** [aws-observability/aws-rum-web#233]
Hello,

We've noticed an error thrown by aws-rum-web client itself in our AWS RUM monitoring (occurred only once so far):

<img width="810" alt="Screenshot 2022-09-19 at 18 32 44" src="https://user-images.githubusercontent.com/16646517/191067653-90cc759f-179d-4686-bbc7-dcff6e2d8a62.png">

The error itself is thrown here: https://github.com/aws-observability/aws-rum-web/blob/1d461c924c188a2fe78e21e5a3dced89e58b42a0/src/dispatch/StsClient.ts#L77

Are there any actions we could take in order to avoid this error? Moreover, would it be possible to include the actual exception being thrown along with the `Failed to retrieve credentials from STS` error message?

**Comment by qhanam** [comment]
This could happen if the first attempt to call STS failed (e.g., due to a network error), but the second attempt succeeded.

> would it be possible to include the actual exception being thrown along with the Failed to retrieve credentials from STS error message?

Yes -- see https://github.com/aws-observability/aws-rum-web/issues/227#issuecomment-1252712017

**Comment by johnw-dev** [comment]
We're seeing this issue on a semi frequent basis as well.  With the updated logging we saw this:

Unhandled Exception: `CWR: Failed to retrieve credentials from STS: TypeError: NetworkError when attempting to fetch resource.`

Is it a performance consideration that we attempt STS assume once?  If not, does it make sense for the library to be updated to perform a retry to reduce incidence of this issue?

**Comment by qhanam** [comment]
The web client makes three attempts before disabling itself. If you are receiving the error in RUM, that means one of the two retries succeeded.

The requests to STS are non-blocking.

Closing as resolved by #272
