### ISSUE TITLE
Include domain as dimension in HttpStatusCodeCount metric

### ISSUE THREAD

**Issue by codermpl** [aws-observability/aws-rum-web#236]
Could we get the domain, host or hostname added as a dimension to the HttpStatusCodeCount metric. Most pages only make requests to a fixed number of domains, so the cardinality of this dimension should reasonable. This would let us filter the metric based on the domain the request go to.

We could do this with a metricFilter on the logs, but that is a pain. Wanting to see your failures broken down by domain seems like a pretty common use case.

I see status and file.type as dimensions already. Those can conceivably have a cardinality in the hundreds, so the domain should be less than that.

See https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-RUM-metrics.html

**Comment by codermpl** [comment]
Hmm, the documentation says "CloudWatch does not aggregate across dimensions for your custom metrics.". That seems really limiting for this. But since HttpStatusCodeCount is an AWS metric, not a custom metric, I guess that doesn't apply.

 https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html#Dimension

**Comment by qhanam** [comment]
Hi @codermpl thanks for the use case!

One workaround is to export the data to CloudWatch Logs and create metric filters on those logs.

At the same time, I'll note this as a feature request :-) .

**Comment by codermpl** [comment]
Thank you. I've started working on that.
