### ISSUE TITLE
Is there a maximum length for a recorded error message?

### ISSUE THREAD

**Issue by kpalmvik** [aws-observability/aws-rum-web#290]
When recording an error, is there a maximum length of the `message` from the [`Error`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error) that can successfully be recorded?

For example:

```javascript
try {
  throw new Error("A message that might be very long...");
} catch (e)
  awsRum.recordError(e);
}
```

The reason I'm asking is that I have encountered errors recorded to CloudWatch RUM simply as _Empty or no message_. One reason could have been that the error message was too long, but I can't find any relevant documentation around this.

**Comment by qhanam** [comment]
Could you provide steps to reproduce? If it can be reproduced with the snippet you provided, how long is "very long"?

**Comment by kpalmvik** [comment]
I hope to be able to reproduce this at some point, but I have not been able to do it so far. 

Hence I take a theoretical approach and wonder if there is a known maximum limit (which wouldn’t be completely unthinkable) that is just not documented. This could very well be completely unrelated to the problem I’m seeing.

**Comment by qhanam** [comment]
Got it, thanks! There are limits on the number of events per (PutRumEvents) request, and per event. However, if you were hitting these you would see the entire event dropped. 

Also consider:
1. It is possible to create an error with no message (e.g., `new Error()`).

1. Different browsers record errors in different ways. For example, Firefox adds filename, lineno and colno to error objects.

1. Different error types (e.g., primitives, Error objects, rejected promises) also contain different information. For example, Error objects generally come with a stack trace, while primitives do not.
