### ISSUE TITLE
AWS RUM Endpoint

### ISSUE THREAD

**Issue by p-obrien** [aws-observability/aws-rum-web#358]
Is it possible to obtain the Endpoint URL programmatically or does it need to be computed?

For example I have Terraform deploying a Cloudwatch RUM and I want to output the data the user needs to configure the Client code with and I can easily obtain the parameters for guestRoleARN and identityPoolID but it appears endpoint needs to be computed. Is this really the case?

**Comment by adebayor123** [comment]
Hi @p-obrien ,

Does Terraform have the regional information while defining infra resources?

If you're referring to the endpoints on the javascript snippet you embed in the HTML files, I would say you just need to create a map with region to endpoint (ex. `us-east-1` -> `https://dataplane.rum.us-east-1.amazonaws.com`) and programmatically update the snippet accordingly. 

Note: the region of the endpoint must be the region where you have defined your app monitor, not web application

**Comment by p-obrien** [comment]
Thanks @adebayor123, 

I couldn't see it exposed by the Terraform provider so I ended up going with the Javascript map which worked.
