### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'version')

### ISSUE THREAD

**Issue by qhanam** [aws-observability/aws-rum-web#382]
@Naes0 observed this error while using cjs with v1.13.3. See #371 

This bug is related to v1.13.x.

**Comment by limhjgrace** [comment]
v1.13.4 mitigates this error. @Naes0 do you mind verifying if the latest release resolves the issue?

**Comment by Naes0** [comment]
@limhjgrace Yep that fixed it thanks a lot 👍
