### ISSUE TITLE
@aws-sdk/querystring-builder is not correctly marked as a dependency.

### ISSUE THREAD

**Issue by chetanDhanvij** [aws-observability/aws-rum-web#403]
### Which web client version did you detect this bug with?

v1.13.3

### What environment (build systems, module system, and framework) did you detect this bug with?

TypeScript v5.0.2, Webpack v4.46.0, ECMAScript modules (ESM) and React v18.2.0

### Is your web application a single page application (SPA) or multi page application (MPA)?

None

### Please provide your web client configuration

{
  allowCookies: true,
  endpoint: "https://dataplane.rum.us-west-2.amazonaws.com",
  guestRoleArn: "arn:aws:iam::000000000000:role/RUM-Monitor-us-west-2-000000000000-00xx-Unauth",
  identityPoolId: "us-west-2:00000000-0000-0000-0000-000000000000",
  sessionSampleRate: 1,
  telemetries: ['errors', 'performance', 'http']
}

### Please describe the bug/issue

Wrt https://github.com/aws-observability/aws-rum-web/issues/328, the issue still exist in latest version. kindly release tag a new version so the fix is available.

**Comment by limhjgrace** [comment]
Hello, we've released the latest version [v1.13.7](https://github.com/aws-observability/aws-rum-web/releases) with the fix for this issue. Could you verify if you're still seeing this issue in the latest release? If not, please feel free to close out this ticket!
