### ISSUE TITLE
[Bug]: Fetch plugin fetches multiple identities before starting

### ISSUE THREAD

**Issue by hannesj** [aws-observability/aws-rum-web#406]
### Which web client version did you detect this bug with?

v1.13.6

### What environment (build systems, module system, and framework) did you detect this bug with?

Remix v1.14.3, Typescript v5.0.4, ECMAScript modules (ESM) and React v18.2.0, aws-rum-web installed as JavaScript Module

### Is your web application a single page application (SPA) or multi page application (MPA)?

SPA

### Please provide your web client configuration

```
{
  "allowCookies":true,
  "enableXRay":true,
  "endpoint":"https://dataplane.rum.eu-north-1.amazonaws.com",
  "guestRoleArn":"arn:aws:iam::account:role/stage-stack-App-AppMonitorUnauthentic1O1WJSN77WOS0",
  "identityPoolId":"eu-north-1:4447b5b0-ebdd-4a73-ace3-ede974be41c3",
  "sessionSampleRate":1,
  "telemetries":[
    "errors",
    "performance",
    ["http", { "addXRayTraceIdHeader": true }]
  ]
}
```

### Please describe the bug/issue

There seems to be some kind of race condition, if the application is installed as a JS module, whereby multiple identities are loaded when starting up the application. I believe this should happen only once. If the script is injected via the script tag, it works as expected with the same config.

![image](https://user-images.githubusercontent.com/698100/233964268-13493857-db09-42a7-a996-dcc812f0b200.png)

![image](https://user-images.githubusercontent.com/698100/233963881-15f31ff2-3c10-4b10-b9d1-2f0d822c9db1.png)

**Comment by adebayor123** [comment]
Hi, can you please show how you initialize the web client in your application? I've seen this happen with users who initialize the web client based on certain conditions, such as clicking on a cart button.

**Comment by adebayor123** [comment]
Is the root.tsx ever invoked more than once? Or to be exact, is the function `Root()` ever invoked more than once? Based on what you have, you initialize the web client and then call `recordPageView`.

But at the same time, I assume when you embed the web client, it's inside the html code in the return statement - is this correct?

**Comment by qhanam** [comment]
There could be a race condition. When the credentials provider is invoked, it [does not check](https://github.com/aws-observability/aws-rum-web/blob/main/src/dispatch/Authentication.ts) if there is an existing request in flight. However, I'm not sure why the credential provider would be invoked multiple times.

If I recall correctly, the web client does a pre-fetch of credentials at startup, and then if needed (i.e., when there is no credential in memory or localStorage) whenever the web client needs to dispatch events.

As @adebayor123 said, this could occur if multiple instances of the web client are being created. This would be the case if React calls Root() more than once (i.e., to re-render the page when the state changes).
