### ISSUE TITLE
[Bug]:  Failed to retrieve Cognito identity: TypeError: response.body.getReader is not a function

### ISSUE THREAD

**Issue by crepers** [aws-observability/aws-rum-web#409]
### Which web client version did you detect this bug with?

v1.13.6

### What environment (build systems, module system, and framework) did you detect this bug with?

TypeScript v4.8.4, ECMAScript modules (ESM) and React v18.2.0

### Is your web application a single page application (SPA) or multi page application (MPA)?

None

### Please provide your web client configuration

...

### Please describe the bug/issue

Hi, Team.

When I tried to build my application, I got an error message like below.

```
    CWR: Failed to retrieve Cognito identity: TypeError: response.body.getReader is not a function

      at CognitoIdentityClient.<anonymous> (node_modules/aws-rum-web/dist/cjs/dispatch/CognitoIdentityClient.js:71:31)
      at step (node_modules/aws-rum-web/dist/cjs/dispatch/CognitoIdentityClient.js:33:23)
      at Object.throw (node_modules/aws-rum-web/dist/cjs/dispatch/CognitoIdentityClient.js:14:53)
      at rejected (node_modules/aws-rum-web/dist/cjs/dispatch/CognitoIdentityClient.js:6:65)
```

**Comment by limhjgrace** [comment]
Hello, it seems like you're having an issue with Cognito. Have you been able to take a look at this [documentation](https://github.com/aws-observability/aws-rum-web/blob/main/docs/cdn_troubleshooting.md#aws-token-vending-cognito-or-sts-fails) to see if it addresses your question?

**Comment by jingjielim** [comment]
I am facing the same issue in jest testing of the app. Don't think it has to do with token vending. The "TypeError: response.body.getReader is not a function" seems like the key error here.

**Comment by adebayor123** [comment]
Hi, what browser are you using to test your application? This happens if the `readableStream` object of NodeJS is different from the one offered by the browser

**Comment by qhanam** [comment]
This sounds like an issue running the web client in a NodeJS environment, which is not supported.

For unit testing, could the fetch function be mocked to contain `readableStream`?
