### ISSUE TITLE
[Feature Request]: User Journey of Actions

### ISSUE THREAD

**Issue by filip-conic** [aws-observability/aws-rum-web#431]
### Please provide your feature request

We are trying to add RUM to our app but would like to see a user journey of the actions a user took, not just the pages visited. Currently, we are hackily treating actions as page views so they appear in the User Journey however this ruins the time spent on page metrics you get.

It would be nice if this a built in feature such that I can log actions that then get aggregated into a user journey the same way page views do.

**Comment by Francydijesi** [comment]
This is something that could be achieved with a funnel analysis. Though this feature has been already internally proposed, it is not in our roadmap for this year. I have created a sim in our backlog to track the request.

**Comment by ps863** [comment]
The request has been forwarded to the RUM service team. Closing this Feature Request as this repo is not used to track service related requests
