### ISSUE TITLE
[Feature Request]: Support in non-commercial regions

### ISSUE THREAD

**Issue by chejimmy** [aws-observability/aws-rum-web#434]
### Please provide your feature request

While it is possible to use RUM in cross region configuration between classic regions, it is no possible in non-commercial regions due to the [1] unreachable endpoints in China (blocked by ICP) or/and [2] lack of cross partition AWS creds.

Please consider adding support in non-commercial regions of CN-NORTH-1 and US-GOV-WEST-1

**Comment by ps863** [comment]
Hi @chejimmy, 
Thank you for the feature request. I will forward this request to the RUM service team and close this request as this repo is not used to track service requests.
