### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by cirigiddaNithish91** [aws-observability/aws-rum-web#474]
### Which web client version did you detect this bug with?

    "aws-rum-web": "^1.16.0",

### What environment (build systems, module system, and framework) did you detect this bug with?

"@angular/compiler": "^16.2.12", "@types/jasmine": "~3.10.18",
    "@types/node": "^18.18.6",   "typescript": "^4.9.3"

### Is your web application a single page application (SPA) or multi page application (MPA)?

None

### Please describe the bug/issue

when i am trying to upgrade the version   aws-rum-web from 1.15.0 to 1.16.0  unit test are failing and unable to find the plugins/types 
 
![Screenshot 2023-12-06 at 12 56 20](https://github.com/aws-observability/aws-rum-web/assets/152087859/b111603a-1579-49ea-ac61-ed73eba940c2)

**Comment by adebayor123** [comment]
@ps863

**Comment by ps863** [comment]
Hi @cirigiddaNithish91 , 
Thank you for reaching out. 
A few questions: 
- Are you attempting to use the TTI plugin? What happens if you exclude the TTI plugin from your web client configuration? 
- Is this causing an issue only with your unit tests or is it impacting telemetry collection? 
- Are you using a CJS application? 
- What unit test framework are you using?

**Comment by ps863** [comment]
Was not able to replicate this on my sample application and its bit difficult without exact details on build system and test framework being. The import in the screenshot is unnecessary and therefore has been removed. 
Will release a patch which should fix this

**Comment by ps863** [comment]
We have released  web client v1.16.1. Please upgrade and try again. 
This change reports the import you shared in the screenshot above and so it should resolve the issue you were seeing. Feel free to re-open the issue if you have more questions/issue is not resolved.
