### ISSUE TITLE
[Bug]: docs example incorrect name for angular errohandler import

### ISSUE THREAD

**Issue by agokhale** [aws-observability/aws-rum-web#485]
### Which web client version did you detect this bug with?

v1.16/HEAD

### What environment (build systems, module system, and framework) did you detect this bug with?

Angular12 (sigh)

### Is your web application a single page application (SPA) or multi page application (MPA)?

SPA

### Please provide your web client configuration

{
  allowCookies: true,
  endpoint: "https://dataplane.rum.us-west-2.amazonaws.com",
  guestRoleArn: "arn:aws:iam::000000000000:role/RUM-Monitor-us-west-2-000000000000-00xx-Unauth",
  identityPoolId: "us-west-2:00000000-0000-0000-0000-000000000000",
  sessionSampleRate: 1,
  telemetries: ['errors', 'performance', 'http']
}

### Please describe the bug/issue

n the  angular expample https://github.com/aws-observability/aws-rum-web/blame/main/docs/cdn_angular.md#L81
The imported name of the reporter object is `RumErrorHandler`
Later in https://github.com/aws-observability/aws-rum-web/blame/24e44674f3670d320f11e0fb3afef8d509f247d3/docs/cdn_angular.md#L96
What I assume is supposed to be that object is called `CwrErrorHander` instead; which should not even build. 
The correction is to L81: s/RumErrorHandler/CwrErrorHandler/
Do you want a PR for this?

**Comment by williazz** [comment]
Nice catch, raised a PR.
