### ISSUE TITLE
[Bug]: RUM stopped sending metrics after some user idle time

### ISSUE THREAD

**Issue by ShawneeY** [aws-observability/aws-rum-web#510]
### Which web client version did you detect this bug with?

v1.13.3

### What environment (build systems, module system, and framework) did you detect this bug with?

TypeScript v5.0.2, Webpack v4.46.0, ECMAScript modules (ESM) and React v18.2.0

### Is your web application a single page application (SPA) or multi page application (MPA)?

SPA

### Please provide your web client configuration

const awsRumConfig = {
            sessionSampleRate: 1,
            guestRoleArn: 'arn:aws:iam::833151442733:role/RUM-Monitor-us-west-2-833151442733-4490992877071-Unauth',
            identityPoolId: 'us-west-2:fa9a3764-de15-4080-813e-b436bf953683',
            endpoint: 'https://dataplane.rum.us-west-2.amazonaws.com',
            telemetries: ['performance', 'errors', 'http', 'interaction'],
            allowCookies: true,
            enableXRay: true
        };

const APPLICATION_ID = '13adb640-125f-4ee1-ad05-871fbc5d6f67';
const APPLICATION_VERSION = '1.0.0';
const APPLICATION_REGION = 'us-west-2';

### Please describe the bug/issue

It appears that RUM stopped sending metrics after some user-idle time.

The POST http_request_type suddenly fixated to `ping` even after reloading:
![ping](https://github.com/aws-observability/aws-rum-web/assets/8426884/17ca4a5c-3e37-4308-9843-aec4cdd9753e)

Is it possible to inform what's going on ?
Does RUM have a debug mode I can turn on to help troubleshoot ?

Thanks

**Comment by williazz** [comment]
Did you breach your `sessionEventLimit`? If so, try again with that set to `0`.

**Comment by ShawneeY** [comment]
Thank you very much! That fixes the issue.
