### ISSUE TITLE
[General Inquiry]: missing stacktrace when recording js errors with RUM

### ISSUE THREAD

**Issue by mcnally** [aws-observability/aws-rum-web#534]
### What is your general inquiry?

I have set up webrum using the script and recordPageView, I am seeing errors in the console e.g. `error Script error.` but no stacktrace
Is there any additional setup required to record error stack traces for errors that happen at runtime ?

**Comment by williazz** [comment]
Please provide steps to reproduce, and the full JS error events

**Comment by qhanam** [comment]
If the application throws something other than an [Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) object (like a string), there will be no stack trace.

For example, `throw "Script error."` will not yield a stack trace.
