### ISSUE TITLE
Unit tests failing with Node.js 16

### ISSUE THREAD

**Issue by qhanam** [aws-observability/aws-rum-web#58]
GitHub is [updating Node.js to version 16](https://github.com/actions/virtual-environments/issues/4446) in all OS images.

Several unit test suites and unit tests fail when run with Node.js 16:

- `Jest worker encountered 4 child process exceptions, exceeding retry limit`
  - CognitoIdentityClient.test.ts
  - BeaconHttpHandler.test.ts
  - StsClient.test.ts
  - Authentication.test.ts
  - CommandQueue.test.ts
- `when a TypeError is thrown then the plugin records the name, message and stack`

To reproduce, run `npm run test` with Node.js 16.

**Comment by qhanam** [comment]
Related to https://developer.ibm.com/blogs/nodejs-15-release-blog/

**Comment by thankyouveryfun** [comment]
I could try to solve this if nobody is on it

**Comment by qhanam** [comment]
Thanks for the offer! I picked this up since it is a CI blocker.

More issues to come...

**Comment by anuraaga** [comment]
> GitHub is updating Node.js to version 16 in all OS images.

Just to confirm, we wouldn't have expected the CI to automatically break since we install a node version, right?

https://github.com/aws-observability/aws-rum-web/blob/main/.github/workflows/ci.yaml#L21

Of course good to fix the build on newer node (and probably can run CI on multiple nodes) but just checking

**Comment by qhanam** [comment]
> Just to confirm, we wouldn't have expected the CI to automatically break since we install a node version, right?

Ah yes you are correct, so the node upgrade is moot. Regardless, this is a bit of a blocker for anyone onboarding using node 16.
