### ISSUE TITLE
[BUG] Javascript snippet error with <script> tags outside of <head> in Chrome

### ISSUE THREAD

**Issue by ckifer** [aws-observability/aws-rum-web#71]
Certain chrome extensions inject script tags in `document` outside and above `head` tags. While this doesn't feel like something RUM should concern itself with it has caused issues sending metrics while using the JS snippet in Chrome.

[Extension example](https://chrome.google.com/webstore/detail/katal-metrics-devtools/nlmhdpeclcbfjhhcmebnealajpkffdni): this extension injects a script via `document.createElement('script')` which inserts outside and above the head tag.

This results in:
![image](https://user-images.githubusercontent.com/25180830/146600160-26b28ac1-f18e-4573-955c-43dc50381d70.png)
when attempting to send metrics to RUM.

Running `document.getElementsByTagName('script')[0];` during a debug session in the middle of the RUM script results in: 
![image](https://user-images.githubusercontent.com/25180830/146600292-6a0c015e-618a-4f78-8e8d-93fd8e06fc25.png)

The easiest way to get around this happening to other customers (even if other chrome extensions don't behave this way) is to have the rum script injected as the first script in `head` rather than `document`. Not sure if this change would have any other implications.

**Comment by qhanam** [comment]
This looks like a good change. A patch will need to be applied to the CloudWatch RUM console, which generates the snippet. I'll bring this to the console team.
