### ISSUE TITLE
Cache cwr.js file from CDN

### ISSUE THREAD

**Issue by blimmer** [aws-observability/aws-rum-web#73]
I'm currently trying out the CloudWatch RUM product. One thing I noticed today is that the https://client.rum.us-east-1.amazonaws.com/1.0.2/cwr.js file is served without any Cache-Control headers:

```
 curl -v https://client.rum.us-east-1.amazonaws.com/1.0.2/cwr.js
*   Trying 65.8.233.80:443...
* Connected to client.rum.us-east-1.amazonaws.com (65.8.233.80) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=client.rum.us-east-1.amazonaws.com
*  start date: Nov 12 00:00:00 2021 GMT
*  expire date: Dec 11 23:59:59 2022 GMT
*  subjectAltName: host "client.rum.us-east-1.amazonaws.com" matched cert's "client.rum.us-east-1.amazonaws.com"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f98b6811000)
> GET /1.0.2/cwr.js HTTP/2
> Host: client.rum.us-east-1.amazonaws.com
> user-agent: curl/7.77.0
> accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200
< content-type: application/javascript
< content-length: 114311
< last-modified: Tue, 23 Nov 2021 00:51:47 GMT
< x-amz-version-id: mQ3VEzOswAhdeQEPxFrH_CGxedkxk4zn
< accept-ranges: bytes
< server: AmazonS3
< date: Sat, 18 Dec 2021 12:39:43 GMT
< etag: "0dfa77fbb42f338ac9955897e9f55641"
< vary: Accept-Encoding
< x-cache: Hit from cloudfront
< via: 1.1 30ea845097208edbc19305c535a5be99.cloudfront.net (CloudFront)
< x-amz-cf-pop: DEN52-C1
< x-amz-cf-id: Vo5ZG0zegHb7QUxU2Iu4PwiIXRBZv3_ibZd5Ack_ZENrsWNgB2kHJQ==
< age: 38372
```

This (rightfully) triggers warnings from Lighthouse:

<img width="751" alt="Screen Shot 2021-12-18 at 4 20 24 PM" src="https://user-images.githubusercontent.com/630449/146658010-23a5c2c0-cdd4-4976-b520-9848326222a7.png">

As you can see from the screenshot, Google Analytics caches for 2 hours but is still flagged. Since the URL for the CloudWatch asset has a version embedded (1.0.2), it seems like this should be safe to cache for at least 24 hours, if not more.

**Comment by hemmachat** [comment]
I second this as we once installed RUM script to our site, the Lighthouse score has dramatically decreased. We also using Next.js and they do not recommend to put any scripts inside the "<head>" section as well.

**Comment by qhanam** [comment]
Thanks for raising this! We have added Cache-Control max-age=604800 headers to full versions (e.g. `1.0.2`) in CDN and Cache-Control max-age=7200 headers to version ranges (e.g., `1.x` and `1.0.x`) in CDN.

Note that it will take up to 24 hours for the CDN for the new header to appear, since the TTL of the files in the CDN cache is 24 hours.

**Comment by blimmer** [comment]
Great, thanks for tackling this. What's the official recommendation for what versioning scheme to use? Phrased another way, how will the snippet appear in the console? Will it recommend "latest major" (e.g. `1.x`) or something else?

**Comment by blimmer** [comment]
Btw, I confirmed the Cache-Control headers appear now. RE: my question above, it looks like the console still recommends a pinned version (1.0.2) for me:

![Screen_Shot_2022-01-14_at_11_14_59_AM](https://user-images.githubusercontent.com/630449/149565319-72ed09b0-ea41-47b4-98c4-4694289f80f9.png)

**Comment by qhanam** [comment]
Currently and for the near future the console will display a specific version, like `1.0.2`, since using a fixed version is a little safer than one that may change automatically.

The console may migrate to using a "latest major" scheme in the code snippet the future.

**Comment by blimmer** [comment]
Sounds good - I'll keep an eye out for changes there.
