### ISSUE TITLE
[Feature request] The retention period be configurable

### ISSUE THREAD

**Issue by zachjonesnoel** [aws-observability/aws-rum-web#78]
The current retention period is currently 30 days, can that be configured where the users can specify "x" days?

**Comment by qhanam** [comment]
Hi @zachjonesnoel thanks for the request ! Am I correct in assuming this request is for the RUM service to support longer retention periods (i.e., after the data has been collected by CloudWatch RUM)?

If so I'll forward it to the RUM service team, as this repo is not used to track service requests.

**Comment by zachjonesnoel** [comment]
Yes @qhanam that is correct! Thanks that would definitely help. I didn't find the relevant GitHub repo so raised an issue here!

**Comment by ckifer** [comment]
@zachjonesnoel If you are backing your RUM metrics to Cloudwatch Logs you should be able to set the log retention period longer than 30 days. That will at least keep the data until this feature is available.
