### ISSUE TITLE
Migrate linter from tslint to eslint

### ISSUE THREAD

**Issue by qhanam** [aws-observability/aws-rum-web#9]
The RUM web client uses [TSLint](https://palantir.github.io/tslint/) as its linter (in pre-commit and continuous integration). However, TSLint is [deprecated](https://blog.palantir.com/tslint-in-2019-1a144c2317a9) and does not support modern ECMAScript.

Onboard [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md) by following the instructions in [tslint-to-eslint-config](https://github.com/typescript-eslint/tslint-to-eslint-config/blob/main/docs/FAQs.md).

Choose an opinionated ESLint config (see [this helpful list](https://github.com/dustinspecker/awesome-eslint#other-prominent-configs-100-stars-or-so)).

See the [Visual Studio Code migration guide](https://code.visualstudio.com/api/advanced-topics/tslint-eslint-migration) for re-configuring VS Code.

**Comment by maniator** [comment]
I have a local branch that I started working on doing this

Is this one a project board somewhere that can be assigned to me? :-)

**Comment by qhanam** [comment]
No one is currently working on this, you're welcome to.

We don't currently use a project board.

**Comment by ZackKanter** [comment]
I believe this was closed by https://github.com/aws-observability/aws-rum-web/pull/234
